const pt = [
  "a", "à", "ao", "aos", "aquela", "aquelas", "aquele", "aqueles", "aquilo", "as", "às",
  "agora", "ainda", "além", "algo", "algumas", "alguns", "ali", "ambas", "ambos", "ano", "anos",
  "ante", "antes", "ao", "aonde", "apenas", "apoio", "após", "aquela", "aquele", "aqui", "aquilo",
  "as", "até", "atrás", "através", "cada", "caminho", "catorze", "cedo", "cento", "certamente",
  "certeza", "cima", "coisa", "com", "como", "conforme", "contra", "contudo", "cuja", "cujas",
  "cujo", "cujos", "da", "daquela", "daquele", "dar", "das", "de", "debaixo", "dela", "delas",
  "dele", "deles", "demais", "dentro", "depois", "desde", "dessa", "desse", "desta", "deste",
  "disse", "disso", "disto", "dito", "diz", "do", "dois", "dos", "doze", "dum", "duma", "durante",
  "e", "ela", "elas", "ele", "eles", "em", "embora", "enquanto", "entre", "era", "eram", "éramos",
  "essa", "essas", "esse", "esses", "esta", "está", "estamos", "estão", "estas", "estava", "estavam",
  "este", "estes", "estive", "estivemos", "estiveram", "estou", "etc", "eu", "exemplo", "faz", "fazeis",
  "fazem", "fazemos", "fazendo", "fazer", "fazia", "fez", "foi", "for", "fora", "foram", "fosse",
  "fossem", "foste", "fostes", "fui", "geral", "grande", "grandes", "haja", "havemos", "havia",
  "hei", "hoje", "hora", "horas", "houve", "houvemos", "houver", "houvera", "houveram", "houverei",
  "houverem", "houveremos", "houveria", "houveriam", "houvermos", "houverá", "houverão", "houveríamos",
  "houvesse", "houvessem", "há", "hão", "isso", "isto", "já", "la", "lá", "lhe", "lhes", "lo", "logo",
  "longe", "lugar", "maior", "mais", "mal", "mas", "me", "mesma", "mesmas", "mesmo", "mesmos",
  "meu", "meus", "minha", "minhas", "momento", "muito", "muitos", "muitas", "na", "nada", "naquela",
  "naquele", "nas", "nem", "nenhum", "nessa", "nesse", "nesta", "neste", "no", "nos", "nós",
  "nossa", "nossas", "nosso", "nossos", "nova", "novas", "novo", "novos", "num", "numa", "nunca",
  "o", "obra", "obrigado", "onde", "ontem", "os", "ou", "outra", "outras", "outro", "outros",
  "para", "parece", "parte", "partir", "pela", "pelas", "pelo", "pelos", "per", "perante", "perto",
  "pode", "pude", "puderam", "podia", "podiam", "podia", "pois", "por", "porém", "porque", "portanto",
  "posso", "pouca", "poucas", "pouco", "poucos", "primeira", "primeiras", "primeiro", "primeiros",
  "própria", "próprias", "próprio", "próprios", "quais", "qual", "qualquer", "quando", "quanto",
  "quantos", "quarta", "quarto", "quatro", "que", "quem", "quer", "quero", "questão", "quieto",
  "quinta", "quinto", "quinze", "sabe", "sabem", "sabemos", "saber", "sabe-se", "são", "se", "seja",
  "sejam", "sem", "sempre", "sendo", "ser", "seria", "seriam", "seu", "seus", "seja", "sim",
  "sistema", "sob", "sobre", "sois", "somente", "somos", "sou", "sua", "suas", "tal", "talvez",
  "também", "tampouco", "tanto", "te", "tem", "tendo", "tenho", "tens", "tentar", "tente", "tentei",
  "tínhamos", "tive", "tivemos", "tiver", "tivera", "tiveram", "tiverem", "tivermos", "tivesse",
  "tivessem", "tiveste", "tivestes", "toda", "todas", "todo", "todos", "trabalha", "trabalho",
  "treze", "três", "tu", "tua", "tuas", "tudo", "tão", "um", "uma", "umas", "uns", "vai", "vais",
  "valor", "veio", "vem", "vêm", "venham", "vens", "ver", "vez", "vezes", "viagem", "vindo", "vinte",
  "vir", "vos", "vós", "vossa", "vossas", "vosso", "vossos", "vários",
  "zero"
];

const en = [
  "a", "about", "above", "after", "again", "against", "all", "am", "an", "and", "any", "are",
  "aren't", "as", "at", "be", "because", "been", "before", "being", "below", "between", "both",
  "but", "by", "can", "can't", "cannot", "could", "couldn't", "did", "didn't", "do", "does",
  "doesn't", "doing", "don't", "down", "during", "each", "few", "for", "from", "further", "had",
  "hadn't", "has", "hasn't", "have", "haven't", "having", "he", "he'd", "he'll", "he's", "her",
  "here", "here's", "hers", "herself", "him", "himself", "his", "how", "how's", "i", "i'd",
  "i'll", "i'm", "i've", "if", "in", "into", "is", "isn't", "it", "it's", "its", "itself", "let's",
  "me", "more", "most", "mustn't", "my", "myself", "no", "nor", "not", "of", "off", "on", "once",
  "only", "or", "other", "ought", "our", "ours", "ourselves", "out", "over", "own", "same", "shan't",
  "she", "she'd", "she'll", "she's", "should", "shouldn't", "so", "some", "such", "than", "that",
  "that's", "the", "their", "theirs", "them", "themselves", "then", "there", "there's", "these",
  "they", "they'd", "they'll", "they're", "they've", "this", "those", "through", "to", "too",
  "under", "until", "up", "very", "was", "wasn't", "we", "we'd", "we'll", "we're", "we've", "were",
  "weren't", "what", "what's", "when", "when's", "where", "where's", "which", "while", "who",
  "who's", "whom", "why", "why's", "with", "won't", "would", "wouldn't", "you", "you'd", "you'll",
  "you're", "you've", "your", "yours", "yourself", "yourselves",

  // Extended common English stopwords
  "above", "afterwards", "almost", "alone", "along", "already", "also", "although", "always",
  "among", "amongst", "amount", "anyhow", "anyone", "anything", "anyway", "anywhere", "around",
  "back", "became", "become", "becomes", "becoming", "beside", "besides", "beyond", "bottom",
  "call", "cannot", "causes", "concerning", "consequently", "consider", "considering",
  "corresponding", "couldnt", "cry", "describe", "detail", "done", "downwards", "during",
  "eg", "eight", "either", "eleven", "else", "elsewhere", "enough", "etc", "even", "ever",
  "everyone", "everything", "everywhere", "except", "few", "fifteen", "fify", "fill", "find",
  "fire", "first", "five", "former", "formerly", "forty", "found", "four", "from", "front",
  "full", "further", "get", "give", "go", "had", "has", "hence", "hereafter", "hereby",
  "herein", "hereupon", "hundred", "indeed", "interest", "into", "itself", "keep", "last",
  "latter", "latterly", "least", "less", "ltd", "made", "many", "may", "meanwhile", "might",
  "mill", "mine", "moreover", "most", "mostly", "move", "much", "must", "name", "namely",
  "neither", "never", "nevertheless", "next", "nine", "nobody", "none", "noone", "nothing",
  "now", "nowhere", "off", "often", "once", "one", "only", "onto", "others", "otherwise",
  "ours", "over", "part", "per", "perhaps", "please", "put", "rather", "re", "same",
  "see", "seems", "serious", "several", "six", "sixty", "somehow", "someone", "something",
  "sometime", "sometimes", "somewhere", "still", "such", "take", "ten", "thence", "thereafter",
  "thereby", "therefore", "therein", "thereupon", "thick", "thin", "third", "thirty", "though",
  "three", "throughout", "thru", "thus", "together", "top", "toward", "towards", "twelve",
  "twenty", "two", "un", "upon", "us", "via", "well", "whatever", "whence", "whenever",
  "whereafter", "whereas", "whereby", "wherein", "whereupon", "wherever", "whether",
  "whither", "within", "without", "yet"
];

const es = [
  "a", "acá", "ahí", "al", "algo", "alguna", "algunas", "alguno", "algunos",
  "allá", "alli", "allí", "ambos", "ante", "antes", "aquel", "aquella", "aquellas", "aquello", "aquellos",
  "aquí", "arriba", "así", "atrás", "aun", "aunque",
  "bajo", "bastante", "bien",
  "cabe", "cada", "casi", "cierta", "ciertas", "cierto", "ciertos", "como", "con", "conmigo",
  "conseguimos", "conseguir", "consigo", "consigue", "consiguen", "consigues",
  "contigo", "contra", "cual", "cuales", "cualquier", "cualquiera", "cualquieras", "cuan",
  "cuando", "cuanta", "cuantas", "cuanto", "cuantos", "de", "dejar", "del", "delante", "demasiado",
  "demás", "dentro", "desde", "después", "detras", "detrás", "día", "donde", "dos", "durante",
  "e", "ejemplo", "el", "él", "ella", "ellas", "ellos", "empleais", "emplean", "emplear", "empleas",
  "empleo", "en", "encima", "entonces", "entre", "era", "eramos", "eran", "eras", "eres", "es",
  "esa", "esas", "ese", "eso", "esos", "esta", "estaba", "estado", "estais", "estamos", "estan",
  "estar", "estas", "este", "esto", "estos", "estoy", "etc", "fin", "fue", "fueron", "fui",
  "fuimos",
  "gueno",
  "ha", "haber", "había", "habéis", "habíamos", "habían", "habías", "hace", "haceis", "hacemos",
  "hacen", "hacer", "haces", "hacia", "haciendo", "han", "hasta", "hay", "haya", "he", "hemos",
  "hicieron", "hizo", "horas", "hoy", "hubo",
  "igual", "incluso", "intenta", "intentais", "intentamos", "intentan", "intentar", "intentas", "intento",
  "ir", "jamás", "junto",
  "la", "lado", "las", "le", "les", "llegar", "llevar", "lo", "los", "luego",
  "mal", "manera", "me", "medio", "mejor", "menos", "mi", "mí", "mía", "mias", "mientras",
  "mio", "míos", "mis", "misma", "mismas", "mismo", "mismos", "modo", "momento", "mucha",
  "muchas", "muchísima", "muchísimas", "muchísimo", "muchísimos", "mucho", "muchos", "muy",
  "nada", "nadie", "ni", "ninguna", "ningunas", "ninguno", "ningunos", "ningún", "no", "nos",
  "nosotras", "nosotros", "nuestra", "nuestras", "nuestro", "nuestros", "nunca",
  "o", "os", "otra", "otras", "otro", "otros",
  "para", "parecer", "parte", "partir", "pasada", "pasado", "pero", "poca", "pocas", "poco", "pocos",
  "podeis", "podemos", "poder", "podria", "podriais", "podriamos", "podrian", "podrias", "por",
  "porque", "primero", "primeros", "propia", "propias", "propio", "propios", "proximo", "próxima",
  "próximas", "próximos", "pudo", "pueda", "puede", "pueden", "puedo", "pues",
  "que", "quedó", "querer", "quien", "quienes", "quiza", "quizas",
  "sabe", "sabeis", "sabemos", "saben", "saber", "sabes", "se", "segun", "segunda", "segundo",
  "seis", "ser", "si", "sí", "siempre", "siendo", "sin", "sino", "so", "sobre", "sois", "sola",
  "solamente", "solas", "solo", "sólo", "solos", "somos", "soy", "su", "sus",
  "tal", "también", "tampoco", "tan", "tanta", "tantas", "tanto", "tantos", "te", "teneis",
  "tenemos", "tener", "tengo", "ti", "tiempo", "tiene", "tienen", "toda", "todas", "todavia",
  "todavía", "todo", "todos", "tomar", "trabaja", "trabajais", "trabajamos", "trabajan", "trabajar",
  "trabajas", "trabajo", "tras", "tres", "tu", "tú", "tus", "tuya", "tuyas", "tuyo", "tuyos",
  "un", "una", "unas", "uno", "unos", "usa", "usais", "usamos", "usan", "usar", "usas", "uso",
  "usted", "ustedes",
  "va", "vais", "valor", "vamos", "van", "varias", "varios", "vaya", "veces", "ver", "verdad",
  "verdadera", "verdadero", "vez", "vosotras", "vosotros", "voy", "vuestra", "vuestras", "vuestro",
  "vuestros",
  "ya", "yo"
];


const fr = [
  "a", "à", "â", "abord", "afin", "ah", "ai", "aie", "aient", "aies", "ailleurs",
  "ainsi", "ait", "allaient", "allo", "allons", "allô", "alors", "anterieur",
  "anterieure", "anterieures", "après", "apres", "as", "assez", "attendu", "au",
  "aucun", "aucune", "aujourd", "aujourd'hui", "aupres", "auquel", "aura",
  "aurai", "auraient", "aurais", "aurait", "auras", "aurez", "auriez", "aurions",
  "aurons", "auront", "aussi", "autre", "autres", "autrui", "aux", "auxquelles",
  "auxquels", "avaient", "avais", "avait", "avant", "avec", "avez", "aviez",
  "avions", "avoir", "avons", "ayant", "ayez", "ayons",
  "b", "bah", "bas", "basee", "bat", "beau", "beaucoup", "bien", "bigre",
  "boum", "bravo", "brrr",
  "c", "ça", "car", "ce", "ceci", "cela", "celle", "celle-ci", "celle-là",
  "celles", "celles-ci", "celles-là", "celui", "celui-ci", "celui-là", "cent",
  "cependant", "certain", "certaine", "certaines", "certains", "certes", "ces",
  "cet", "cette", "ceux", "ceux-ci", "ceux-là", "chacun", "chacune", "chaque",
  "cher", "chère", "chères", "chers", "chez", "chiche", "chut", "ci", "cinq",
  "cinquantaine", "cinquante", "cinquantième", "cinquième", "clac", "clic", "combien",
  "comme", "comment", "comparable", "comparables", "compris", "concernant",
  "contre", "couic", "crac", "d", "da", "dans", "de", "debout", "dedans", "dehors",
  "delà", "depuis", "derrière", "des", "desormais", "desquelles", "desquels",
  "dessous", "dessus", "deux", "deuxième", "deuxièmement", "devant", "devers",
  "devra", "devrait", "different", "differentes", "differents", "différent",
  "différente", "différentes", "différents", "dire", "directe", "directement",
  "dit", "dite", "dits", "divers", "diverse", "diverses", "doit", "doivent", "donc",
  "dont", "dos", "douze", "dring", "du", "duquel", "durant",
  "e", "effet", "egale", "egalement", "egales", "eh", "elle", "elle-même", "elles",
  "elles-mêmes", "en", "encore", "enfin", "entre", "envers", "environ", "es", "ès",
  "est", "et", "etant", "etc", "etre", "eu", "euh", "eux", "eux-mêmes", "exactement",
  "excepté",
  "f", "façon", "fais", "faisaient", "faisant", "fait", "faites", "faudra", "faudrait",
  "faut", "feront", "fi", "flac", "floc", "fois", "font",
  "g", "gens", "h", "ha", "hé", "hein", "hélas", "hem", "hep", "hi", "ho", "holà",
  "hop", "hormis", "hors", "hou", "houp", "hue", "hui", "huit", "huitième",
  "hum", "hurrah",
  "i", "il", "ils", "importe", "j", "je", "jusqu", "jusque", "k", "l", "la",
  "là", "laquelle", "las", "le", "lequel", "les", "lès", "lesquelles", "lesquels",
  "leur", "leurs", "longtemps", "lors", "lorsque", "lui", "lui-même",
  "m", "ma", "maint", "mais", "malgré", "me", "même", "mêmes", "merci", "mes",
  "mien", "mienne", "miennes", "miens", "mille", "mince", "moi", "moi-même",
  "moins", "mon", "moyennant",
  "n", "na", "ne", "néanmoins", "neuf", "neuvième", "ni", "nombreuses", "nombreux",
  "non", "nos", "notamment", "notre", "nôtre", "nôtres", "nous", "nous-mêmes",
  "nul", "o", "o|", "ô", "oh", "ohé", "olé", "ollé", "on", "ont", "onze", "onzième",
  "ore", "ou", "où", "ouf", "ouias", "oust", "ouste", "outre", "p", "paf", "pan",
  "par", "parce", "parfois", "parle", "parlent", "parler", "parmi", "partant",
  "pas", "passé", "pendant", "personne", "peu", "peut", "peuvent", "peux",
  "pff", "pif", "plein", "plouf", "plus", "plusieurs", "plutôt", "pouah", "pour",
  "pourquoi", "premier", "près", "proche", "psitt", "puis", "puisque",
  "q", "qu", "quand", "quant", "quanta", "quant-à-soi", "quarante", "quatorze",
  "quatre", "quatrième", "quatrièmement", "que", "quel", "quelle", "quelles",
  "quelqu'un", "quelque", "quelques", "quels", "qui", "quiconque", "quinze",
  "quoi", "quoique", "r", "revoici", "revoilà", "rien",
  "s", "sa", "sacrebleu", "sans", "sapristi", "sauf", "se", "seize", "selon",
  "semblable", "semblaient", "semble", "semblent", "sent", "sept", "septième",
  "sera", "serai", "seraient", "serais", "serait", "seras", "serez", "seriez",
  "serions", "serons", "seront", "ses", "seul", "seule", "seulement", "si",
  "sien", "sienne", "siennes", "siens", "sinon", "six", "sixième", "soi",
  "soi-même", "soient", "sois", "soit", "soixante", "sommes", "son", "sont",
  "sous", "souvent", "soyez", "soyons", "suis", "suivant", "sur", "surtout",
  "t", "ta", "tac", "tant", "te", "té", "tel", "telle", "tellement", "telles",
  "tels", "tenant", "tes", "tic", "tien", "tienne", "tiennes", "tiens", "toc",
  "toi", "toi-même", "ton", "touchant", "toujours", "tous", "tout", "toute",
  "toutefois", "toutes", "treize", "trente", "très", "trois", "troisième",
  "troisièmement", "trop", "tsoin", "tsouin", "tu",
  "u", "un", "une", "unes", "uns", "v", "va", "vais", "valeur", "vas", "vers",
  "via", "vif", "vifs", "vingt", "vivat", "vive", "vives", "vlan", "voici",
  "voilà", "vont", "vos", "votre", "vous", "vous-mêmes", "vu", "w", "x", "y",
  "z", "zut"
];


const eo = [
  "aŭ", "ajn", "al", "ankoraŭ", "antaŭ", "apud", "at",
  "ĉar", "ĉe", "ĉi", "ĉiu", "ĉiuj", "ĉiujn", "ĉion", "ĉies", "ĉiel", "ĉiam", "ĉio", "ĉiuĵaŭde",
  "da", "de", "dek", "dum",
  "eble", "ekde", "ekster", "en", "estas", "estis", "estos", "estus", "estante", "estanta", "estu",
  "for", "fine", "foje",
  "ĝis", "ĝi", "ĝia", "ĝiaj", "ĝian", "ĝias", "ĝin", "ĝis",
  "ha", "havas", "havis", "havos", "havus", "havi", "havas", "havanta", "havante",
  "ial", "iam", "ie", "iel", "ies", "iom", "iomete", "inter",
  "ja", "jam", "je", "jen", "ju", "ĵus",
  "kaj", "ke", "kiel", "kio", "kiom", "kie", "kiu", "kies", "kiuj", "kiun", "kiom",
  "kontraŭ", "kun",
  "la", "li", "lia", "liaj", "lian", "lias", "lin", "loĝi", "loĝas",
  "malantaŭ", "malgraŭ", "maniere", "mem", "miaj", "mian", "mi", "mia", "mien", "min", "miaj", "miajn", "mio",
  "multaj", "multe", "multa", "multaĵojn",
  "ne", "nek", "ni", "nia", "niaj", "nian", "nin", "niajn", "novaj",
  "nu",
  "ol", "oni", "onidire",
  "per", "pli", "plu", "por", "post", "pri", "pro",
  "sama", "sed", "sen", "sia", "siaj", "sian", "sias", "sin", "siajn",
  "sub", "super", "sur",
  "tia", "tiaj", "tian", "tie", "tiel", "tiom", "tiu", "tiuj", "tiun", "ties", "tio", "tiomete",
  "tra", "tre", "trop", "tro", "tuj",
  "unu", "unufoje", "unuajn",
  "vi", "via", "vian", "viaj", "vin", "viajn", "viaj",
  "ĉu", "sen"
];

const ru = [
  "а", "без", "более", "бы", "был", "была", "были", "было", "быть",
  "в", "вам", "вас", "весь", "во", "вот", "все", "всего", "всех", "вы",
  "где", "да", "даже", "для", "до", "его", "ее", "если", "есть", "еще",
  "ж", "же", "за", "зачем", "здесь", "и", "из", "или", "им", "иметь", "их",
  "к", "как", "какая", "какой", "когда", "кто", "куда",
  "ли", "либо",
  "мне", "много", "многочисленная", "многочисленные", "многочисленный", "мной", "многое", "может",
  "можно", "мой", "моя", "моё", "мы",
  "на", "над", "надо", "наш", "наша", "наше", "наши", "не", "него", "нее", "ней", "нельзя",
  "нет", "ни", "нибудь", "ним", "них", "но", "ну",
  "о", "об", "однако", "он", "она", "они", "оно", "от", "очень",
  "по", "под", "после", "потом", "потому", "почти", "при", "про",
  "раз", "разве", "с", "сам", "сама", "сами", "само", "самого", "самой", "свою", "себе", "себя",
  "сегодня", "сейчас", "си", "сказал", "сказала", "сказать", "со", "совсем", "так", "такая", "также",
  "таки", "такой", "там", "тебя", "тем", "теми", "теперь", "тех", "то", "тобой", "тобою", "тогда", "того",
  "тоже", "той", "только", "том", "тот", "три", "тут", "ты",
  "у", "уж", "уже",
  "хорошо",
  "хотя", "чего", "чей", "чем", "через", "что", "чтоб", "чтобы", "чье", "чья", "чьи",
  "эта", "эти", "это", "этот", "эту", "я"
];

const zh = [
  "的", "了", "在", "是", "我", "有", "和", "就", "不", "人",
  "都", "一", "一个", "上", "也", "很", "到", "说", "要", "去",
  "你", "会", "着", "没有", "看", "好", "自己", "这", "那", "还",
  "对", "能", "而", "着", "下", "过", "地", "他", "她", "它",
  "我们", "你们", "他们", "她们", "它们",
  "什么", "吗", "呢", "吧", "啊", "哦", "恩",
  "被", "给", "从", "向", "于", "把", "比", "并", "则", "却",
  "很", "再", "更", "最", "又", "已", "已經", "正在", "一直", "一起",
  "因为", "所以", "如果", "但是", "虽然", "而且", "或者", "还是",
  "怎么", "怎么着", "怎么样", "怎样", "哪个", "哪儿", "哪里", "谁",
  "呢", "吗", "呀", "哇", "啦",
  "这儿", "那儿", "这里", "那里", "这些", "那些", "这种", "那种",
  "东西", "时候", "地方", "情况",
  "啊", "呀", "吧", "吗", "嘛",
  "每", "各", "及", "其", "即", "等", "等等", "与",
  "为了", "根据", "由于", "通过", "关于",
  "因此", "然而", "另外", "同时", "然后", "后来", "之前", "之后",
  "多少", "多么", "几", "几乎", "一些", "所有"
];

const vi = [
  "ai", "anh", "ba", "bà", "bác", "bạn", "bằng", "bị", "biết", "bao", "bao giờ",
  "bây", "bây giờ", "bởi", "cả", "các", "cái", "cần", "càng", "có", "có thể",
  "có vẻ", "có khi", "có điều", "có điều gì", "có lẽ", "có ai", "có gì", "có đâu",
  "cô", "công", "cùng", "cũng", "cứ", "cứu",
  "chắc", "chỉ", "chiếc", "cho", "chưa", "chuyện", "chúng", "chúng ta", "chúng tôi", "chúng mình",
  "chính", "chị", "chia", "chịu", "cho đến", "cho rằng", "cho nên", "chỗ",
  "cái gì", "cái nào", "cái ấy",
  "đã", "đang", "đây", "đấy", "được", "đến", "đi", "điều", "do", "dưới",
  "dù", "dường như", "đó", "được rồi", "để", "đều",
  "gì", "giờ", "giữa", "gần", "gặp", "gồm",
  "hay", "họ", "hoặc", "hết", "hơn", "hoàn toàn", "hãy",
  "khi", "khi nào", "khoảng", "khác", "không", "không ai", "không gì", "không những", "không thể",
  "là", "lại", "làm", "lắm", "lần", "lên", "lúc", "lúc nào", "luôn", "luôn luôn",
  "mà", "mình", "mọi", "mọi người", "mọi thứ", "mọi cái",
  "một", "một ít", "một số", "một vài", "một cách", "mỗi", "mới",
  "nào", "này", "nấy", "nên", "nếu", "nơi", "nào đó", "nơi nào", "nơi đây", "nơi ấy",
  "ngay", "ngày", "ngày nào", "ngày mai", "ngày nay", "ngày xưa", "ngày đó", "người", "người nào",
  "người ta", "người ấy", "người này", "người kia", "người khác", "nhà", "nhưng", "như", "như là", "như vậy",
  "nhiều", "nhiều khi", "những", "những gì", "những ai", "những cái",
  "nó", "nơi đâu",
  "rằng", "rất", "ra", "rồi", "rõ",
  "sau", "sao", "sẽ", "sự", "sao cho", "song", "so với", "số",
  "ta", "tại", "theo", "thì", "thế", "thế nào", "thế này", "thế kia", "thế đó",
  "thành", "thành ra", "thành thử", "thành phần", "thật", "thật ra", "thật sự", "thấy", "thêm",
  "trên", "trong", "trước", "trước đây", "trước đó", "trước khi", "trước tiên",
  "từng", "tự", "từ", "tại sao", "tại vì",
  "và", "vào", "vậy", "về", "vì", "với", "vừa",
  "xa", "xem", "xảy ra"
];

const ro = [
  "a", "abia", "acea", "aceasta", "această", "aceea", "acei", "aceia", "acel", "acela",
  "acele", "acelea", "acest", "acesta", "aceşti", "aceştia", "acolo", "acum", "ai", "aia", "al",
  "ale", "alea", "alt", "alta", "altceva", "alte", "altfel", "alti", "altii", "altul",
  "am", "anume", "apoi", "ar", "are", "asupra", "au", "avea", "avem", "aveţi", "avut",
  "azi",
  "bai", "bă", "bine",
  "ca", "cam", "capat", "care", "carea", "carei", "carora", "caruia", "cat", "catre", "caut",
  "ce", "cea", "cei", "ceilalti", "cel", "cele", "celor", "ceva", "chiar", "ci", "cinci",
  "cînd", "cind", "cine", "cineva", "cit", "cît", "cita", "cîte", "cîteva", "cîtva", "cîtă",
  "contra", "cu", "cum", "cumva", "curând", "curînd",
  "da", "daca", "dacă", "dar", "dat", "datorită", "de", "deasupra", "deci", "decât", "decit",
  "deja", "deoarece", "desi", "despre", "din", "dinaintea", "dintr", "dintre", "doar", "doi",
  "doilea", "drept", "dupa", "după",
  "ea", "ei", "el", "ele", "era", "este", "eti", "eu", "exact",
  "face", "fara", "fără", "fata", "fi", "fie", "fiecare", "fii", "fim", "fiu", "fiţi", "foarte",
  "fost",
  "graţie",
  "hai", "iar", "ieri", "ii", "il", "imi", "în", "îmi", "îl", "împotriva", "înainte", "înca",
  "încă", "încît", "încât", "între", "îţi", "iti", "îi", "însă",
  "la", "le", "li", "lor", "lui", "lângă",
  "mai", "mare", "mea", "mei", "mele", "mereu", "meu", "mi", "mie", "mine", "mod", "mult", "multa",
  "multe", "multi", "mulţi", "multă", "multumesc",
  "ne", "nevoie", "ni", "nici", "niciodata", "nicăieri", "niciun", "niciuna", "nicio", "niciunul",
  "nimeni", "nimic", "niste", "nişte", "noastre", "noastră", "noi", "noroc", "nostru", "nou", "noua",
  "nouă", "nu",
  "numai",
  "odata", "odată", "or", "ori", "oricare", "orice", "oricine", "oricum", "oricând", "oricat",
  "oricât", "oriceva", "oriunde",
  "pana", "până", "pe", "pentru", "peste", "pic", "pina", "plus", "poate", "pot", "prea",
  "prima", "primul", "prin", "printr", "putini", "puţin", "puţina", "puţină",
  "sa", "să", "sai", "sale", "sau", "se", "sea", "si", "şi", "sint", "sînt", "sîntem", "sînteţi",
  "sunt", "suntem", "sunteţi", "sus",
  "ta", "tale", "te", "ti", "tie", "timp", "toata", "toate", "toată", "tocmai", "tot", "toti", "toţi",
  "totul", "totusi", "totuşi", "tu", "tuturor",
  "un", "una", "unde", "undeva", "unei", "unele", "uneori", "unii", "unor", "unui", "unu", "unul",
  "va", "vă", "vi", "voastre", "voastră", "voi", "vom", "vor", "vostru", "vouă", "vreo", "vreun",
  "zi", "zice"
];

const ko = [
  "그", "그리고", "그러나", "그러면", "그러므로", "그런데", "그럼", "그때", "그렇지만",
  "또", "또는", "또한", "등", "따라서", "때문에", "때문에", "만약", "만일",
  "모든", "무엇", "뭐", "뭐든", "뭘", "및", "바로", "보다", "보다는",
  "뿐", "뿐만", "사실", "서로", "아니", "아니라", "아니면", "아마", "아직",
  "아직도", "아예", "아울러", "아하", "어떤", "어느", "어느덧", "어디", "어디든",
  "어떻게", "언제", "언제나", "얼마", "얼마나", "예", "예를", "오직", "우리",
  "우선", "원래", "위해", "이", "이것", "이것들", "이런", "이렇게", "이때",
  "이외에", "이후", "인해", "일단", "잘", "저", "저것", "저기", "저쪽",
  "저희", "전혀", "절대", "정도", "조금", "좀", "종종", "주로", "즉",
  "지금", "지금까지", "지속", "지체없이", "지하여", "진짜", "차라리", "처음", "첫째",
  "총", "통해", "특히", "하나", "하는", "하니", "하지만", "하자", "혹은",
  "혹시", "혹은", "후", "훨씬"
];

const de = [
  "aber", "alle", "allem", "allen", "aller", "alles",
  "als", "also", "am", "an", "ander", "andere", "anderem", "anderen", "anderer", "anderes",
  "anderm", "andern", "anderr", "anders",
  "auch", "auf", "aus",
  "bei", "bin", "bis", "bist",
  "da", "damit", "dann", "das", "dass", "dasselbe",
  "davon", "dazu", "dein", "deine", "deinem", "deinen", "deiner", "deines",
  "den", "denn", "der", "derer", "dessen",
  "deshalb", "die", "dies", "diese", "diesem", "diesen", "dieser", "dieses",
  "doch", "dort", "du", "durch",
  "ein", "eine", "einem", "einen", "einer", "eines",
  "einig", "einige", "einigem", "einigen", "einiger", "einiges",
  "einmal", "er", "ihn", "ihm", "es",
  "etwas", "euer", "eure", "eurem", "euren", "eurer", "eures",
  "für",
  "gegen", "gewesen", "hab", "habe", "haben", "hat", "hatte", "hatten",
  "hier", "hin", "hinter",
  "ich", "ihm", "ihn", "ihr", "ihre", "ihrem", "ihren", "ihrer", "ihres",
  "im", "in", "indem", "ins", "ist",
  "jede", "jedem", "jeden", "jeder", "jedes",
  "jene", "jenem", "jenen", "jener", "jenes",
  "jetzt",
  "kann", "kein", "keine", "keinem", "keinen", "keiner", "keines",
  "können", "könnte",
  "machen", "man", "manche", "manchem", "manchen", "mancher", "manches",
  "mein", "meine", "meinem", "meinen", "meiner", "meines",
  "mit", "muss", "musste",
  "nach", "nicht", "nichts", "noch", "nun", "nur",
  "ob", "oder", "ohne",
  "sehr", "sein", "seine", "seinem", "seinen", "seiner", "seines",
  "selbst", "sich", "sie", "ihnen", "sind", "so", "solche", "solchem", "solchen", "solcher", "solches",
  "soll", "sollte",
  "sondern", "sonst",
  "über", "um", "und", "uns", "unser", "unsere", "unserem", "unseren", "unserer", "unseres",
  "unter",
  "viel", "vom", "von", "vor",
  "während", "war", "waren", "warst", "was", "weg", "weil", "weiter", "welche", "welchem",
  "welchen", "welcher", "welches",
  "wenn", "werde", "werden", "wie", "wieder", "will", "wir", "wird", "wirst", "wo", "wollen", "wollte",
  "würde", "würden",
  "zu", "zum", "zur", "zwar", "zwischen"
];


const fi = [
  "aiemmin", "aika", "aikaa", "aikaan", "aikaisemmin", "aikaisin",
  "aina", "ainakin", "ainoa", "ainoat", "aiomme", "aion", "aist",
  "ajankohtaista", "ajatella", "aktiivisesti", "alla", "alle",
  "aloittaa", "ansiosta", "antaa", "apu", "asia", "asioiden",
  "asti", "avulla",
  "edes", "ehkä", "ei", "eikä", "eilen", "eli", "ellei", "ellemme", "ellen",
  "elleivät", "elleivätkö", "emme", "en", "enää", "enemmän",
  "ennen", "ensi", "ensimmäinen", "ensimmäiseksi", "ensimmäisen",
  "eri", "erittäin", "esimerkiksi",
  "halua", "haluaa", "he", "heidän", "heidät", "heihin", "heille",
  "heiltä", "heissä", "heistä", "heitä", "helposti", "heti", "hetkellä",
  "hieman", "hän", "häneen", "hänellä", "hänelle", "häneltä", "hänen",
  "hänessä", "hänestä", "hänet",
  "ihan", "ilman", "itse", "itsensä", "ja", "jo", "joka", "jokainen",
  "jokin", "joko", "joku", "jolla", "jolle", "jolloin", "jolta", "jompikumpi",
  "jonka", "jonkin", "jonne", "jos", "joskus", "jossa", "josta", "jotain",
  "joten", "jotenkin", "jotenkuten", "jotka", "jotta", "joudu", "joutua",
  "joutuu", "jolloin", "jälkeen", "jälleen", "juuri",
  "kaikki", "kaiken", "kaikille", "kaikilta", "kaikissa", "kaikista",
  "kaikkea", "kaikkiin", "kanssa", "kauan", "kautta", "kehen", "keiden",
  "keihin", "keille", "keiltä", "keissä", "keistä", "keitä", "keneen",
  "kenelle", "keneltä", "kenen", "kenessä", "kenestä", "kenet", "kennessä",
  "kenties", "kerran", "kerta", "keskellä", "kesken", "koko", "koska",
  "koskaan", "kovin", "kuin", "kuinka", "kuitenkaan", "kuitenkin",
  "kuka", "kukaan", "kukin", "kumpi", "kun", "kuten", "kuuden", "kuusi",
  "kyllä",
  "lisäksi", "lisää", "lla", "luona", "mahdollisimman", "mahdollista",
  "me", "meidän", "meidät", "meihin", "meille", "meiltä", "meissä",
  "meistä", "meitä", "melkein", "mikä", "mikäli", "mikään", "mikin",
  "miksi", "milloin", "milloinkin", "minä", "minun", "minut", "minua",
  "minuun", "minulle", "minulta", "minussa", "minusta", "missä", "mistä",
  "miten", "mitkä", "moi", "moni", "monia", "monien", "monilla", "monilta",
  "muassa", "muiden", "muille", "muilta", "mukaan", "mukaansa",
  "mukana", "mutta", "muu", "muut", "muuta", "muutama", "myös",
  "myöhemmin", "myös", "myöskään", "myöskin",
  "ne", "niiden", "niihin", "niille", "niillä", "niiltä", "niissä", "niistä", "niitä",
  "noin", "nopeasti", "nopein", "nuo", "nyt",
  "ole", "olemme", "olen", "olet", "olette", "oleva", "olevan", "oli",
  "olimme", "olisi", "olisimme", "olisin", "olisit", "olisitte", "olisivat",
  "olit", "olitte", "olivat", "olla", "olleet", "ollut", "oma", "omaa",
  "omaan", "omassa", "omia", "omiin", "omien", "omille", "omilta",
  "omissa", "omista", "on", "onkin", "onko", "ovat", "paljon",
  "paremmin", "peräti", "pidä", "pieni", "poikki", "puolesta",
  "päälle", "runsaasti",
  "saada", "sai", "samaa", "samalla", "samaan", "saman", "samassa",
  "samat", "samoin", "sanoa", "sanoi", "sanoo", "sitä", "siihen",
  "siinä", "siitä", "sillä", "sille", "siltä", "sinä", "sinun", "sinut",
  "sinua", "sinuun", "sinulle", "sinulta", "sinussa", "sinusta",
  "sitten", "siksi", "sillä", "silläkin", "silloin", "silti",
  "sinne", "siellä", "sieltä", "todella", "tosin", "tuhat", "tule",
  "tulee", "tulevat", "tuli", "tulin", "tulla", "tällä", "tällöin",
  "tämä", "tämän", "tänä", "tänään", "tässä", "tästä", "täten", "täksi",
  "tällä", "tälle", "tältä", "tällainen", "tällöin",
  "tuo", "tuolla", "tuolloin", "tuonne", "tuossa", "tuosta", "tuotä",
  "tuskin", "tykö",
  "vaan", "vai", "vaikea", "vaikka", "vain", "varmasti", "varsinkin",
  "varten", "vasen", "vielä", "viime", "voi", "voidaan", "voimme",
  "voin", "voisi", "voit", "voitte", "voivat", "vuoksi",
  "yhdessä", "yhdeksän", "yhden", "yhtä", "yhtäällä", "yhtään",
  "yhteen", "yhteensä", "yhteydessä", "yksi", "yksin", "yksittäinen",
  "yleensä", "ylemmäs", "yli", "ylös", "ympäri", "ynnä"
];

const ar = [
  "أ", "إ", "آ", "ابتداء", "اثر", "اجل", "احد", "اذا", "اذا ما", "اذن",
  "اربع", "ارتد", "استحال", "اشد", "اف", "اكثر", "اكد", "الا", "الاخيرة",
  "الان", "الى", "الاول", "الاولى", "التى", "التي", "الثاني", "الثانية",
  "الذي", "الذين", "الذيت", "الذيتان", "الذيتين", "الذيذ", "الذين",
  "اللائي", "اللائي", "اللتي", "اللاتي", "اللتان", "اللتين",
  "اللذان", "اللذين", "اللائي", "اللواتي", "اما", "امام", "امس", "امسى",
  "امكن", "امّا", "ان", "انبرى", "انقلب", "انه", "انها", "انهم", "انني",
  "انني", "انّى", "او", "اول", "اي", "اى", "اية", "ايضا", "ايّ", "ايّان",
  "ب", "بات", "باسم", "بان", "بخ", "برس", "بسبب", "بس", "بشكل", "بضع",
  "بط", "بعد", "بعض", "بغض", "بل", "بلا", "بلى", "بين",
  "ت", "تحت", "تحوّل", "ترك", "تعلّق", "تلك", "تم", "تمّ", "ثم", "ثمّ",
  "جعل", "جلل", "جميع", "جمع", "جهة",
  "حاشا", "حتى", "حيث", "حيثما", "حين", "حول",
  "خلا", "خلال", "خير",
  "دون", "دونما",
  "ذا", "ذات", "ذاك", "ذان", "ذانك", "ذلك", "ذلكم", "ذلكما", "ذلكن",
  "ذه", "ذو", "ذوا", "ذوات", "ذيت", "ذيتا", "ذيتان", "ذيتين", "ذين",
  "ذينك",
  "رأى", "رجع", "روح", "رغم",
  "زال", "زعم", "زيارة",
  "س", "سا", "صار", "صباح", "صارت", "صير",
  "ضد", "ضمن", "ظل", "ظلت", "ظن",
  "عاد", "عام", "عامة", "عبر", "عل", "على", "عليه", "عليها", "عليهم",
  "عن", "عند", "عندما", "عنه", "عنها", "عني", "عنهم", "عسى", "غير",
  "ف", "فان", "فانه", "فكانت", "فلا", "فلم", "فليكن", "فما", "فمن",
  "فهو", "في", "فيم", "فيما", "فين", "فيها", "قد", "قبل", "قدر",
  "قط", "قلما", "قوة", "كأن", "كأنما", "كاد", "كان", "كانت", "كذا",
  "كذلك", "كلا", "كلاهما", "كلتا", "كليكما", "كل", "كلاهما", "كلها",
  "كم", "كما", "كي", "كيف", "كيفما",
  "ل", "لا", "لاسيما", "لدى", "لست", "لستم", "لستما", "لستن", "لسن",
  "لسنا", "لعل", "لك", "لكم", "لكما", "لكن", "لكنما", "لكي", "لما",
  "لم", "لمّا", "لن", "له", "لها", "لو", "لولا", "لوما", "لي", "لهم",
  "لنا", "ليس", "ليسا", "ليست", "ليسا", "ليستا", "ليست", "ليسو",
  "ما", "ماذا", "مازال", "متى", "مثل", "مذ", "مد", "مر", "مع", "مما",
  "من", "منذ", "مه", "مهما",
  "نحو", "نحن", "نفس", "نهاية", "نعم", "نفسه", "نفسها", "نفسهم",
  "هؤلاء", "ها", "هاتان", "هاته", "هاتي", "هاتين", "هاك", "هاهنا",
  "هذا", "هذه", "هذي", "هذين", "هذان", "هكذا", "هل", "هلا", "هم",
  "هما", "هن", "هنا", "هناك", "هنالك", "هو", "هي", "هيا", "هيهات",
  "و", "وإذ", "وأما", "وأنت", "وأنتما", "وأنا", "وأنتن", "وقد", "وكأن",
  "ولكن", "ولو", "ومن", "وهب", "وهو", "ويكأن",
  "يا"
];


const el = [
  "αλλά", "αν", "αντί", "από", "αφού",
  "για", "γιὰ", "γύρω",
  "δε", "δεν", "διὰ", "διά", "διότι",
  "εάν", "εγώ", "είμαι", "είναι", "είσαι", "είστε", "είμαστε",
  "εν", "ενώ", "επί", "έτσι", "έως",
  "έχω", "έχει", "έχουν", "είχε", "είχαν",
  "θα", "ιδίως", "ίσως", "ίσως",
  "κατά", "κάθε", "καθώς", "και", "κι", "κάτι", "κάποια", "κάποιοι", "κάποιο", "κάποιος",
  "κιόλας", "κοντά", "κρατάει", "κυρίως",
  "λέει", "λοιπόν", "λόγω",
  "μάλιστα", "μα", "μαζί", "με", "μεταξύ", "μέχρι", "μη", "μην", "μηδέ",
  "μόνο", "μόνον", "μου", "μου", "μέσα",
  "να", "ναι", "νέα", "νέοι",
  "ο", "οι", "όμως", "όλα", "όλοι", "όλος", "όποιος", "όπου", "όπως", "όσο", "όσοι", "όταν", "ότι", "όχι",
  "παρά", "πάντα", "πάνω", "περίπου", "περί", "πιο", "πλέον", "ποια", "ποιες", "ποιο", "ποιοι", "ποιος",
  "πολλά", "πολλοί", "πολύ", "που", "πότε", "πριν", "προς",
  "πως", "πόσο", "πώς",
  "σε", "σου", "σας", "συγκεκριμένα", "συν", "σχετικά",
  "τα", "την", "της", "τι", "τις", "το", "τον", "τους", "του", "των",
  "τόσο", "τότε", "τώρα",
  "υπέρ", "υπό",
  "χωρίς"
];


const theological_pt = ["senhor", "jesus", "cristo", "deus", "amem", "aleluia", "espirito", "santo", "maria", "pai", "filho", "salvador", "messias", "yahweh", "jeová"];
const theological_en = ["lord", "jesus", "christ", "god", "amen", "hallelujah", "holy", "spirit", "mary", "father", "son", "savior", "messiah", "yahweh", "jehovah"];
const theological_es = ["señor", "jesús", "cristo", "dios", "amén", "aleluya", "espíritu", "santo", "maría", "padre", "hijo", "salvador", "mesías", "yahveh", "jehová"];
// ... defina as outras listas teológicas para cada idioma ...
const theological_fr = ["seigneur", "jésus", "christ", "dieu", "amen", "alléluia", "esprit", "saint", "marie", "père", "fils", "sauveur", "messie", "yahvé", "jéhovah"];
const theological_eo = ["sinjoro", "jesuo", "kristo", "dio", "amen", "haleluja", "sankta", "spirito", "maria", "patro", "filo", "savanto", "mesio", "jahveo", "jehovo"];
const theological_ru = ["господь", "иисус", "христос", "бог", "аминь", "аллилуйя", "святой", "дух", "мария", "отец", "сын", "спаситель", "мессия", "яхве", "иегова"];
const theological_zh = ["主", "耶稣", "基督", "上帝", "阿门", "哈利路亚", "圣灵", "圣", "马利亚", "父", "子", "救主", "弥赛亚", "雅威", "耶和华"];
const theological_vi = ["chúa", "giê-su", "đấng", "cơ-đốc", "đức", "chúa trời", "amen", "ha-lê-lu-gia", "thánh", "thần", "ma-ri-a", "cha", "con", "cứu-chúa", "mê-si", "giê-hô-va"];
const theological_ro = ["domnul", "iisus", "hristos", "dumnezeu", "amin", "aleluia", "sfânt", "duh", "maria", "tată", "fiu", "mântuitor", "mesia", "yahweh", "iehova"];
const theological_ko = ["주", "예수", "그리스도", "하나님", "아멘", "할렐루야", "성령", "성", "마리아", "아버지", "아들", "구세주", "메시아", "야훼", "여호와"];
const theological_de = ["herr", "jesus", "christus", "gott", "amen", "halleluja", "heilig", "geist", "maria", "vater", "sohn", "erretter", "messias", "jahwe", "jehova"];
const theological_fi = ["herra", "jeesus", "kristus", "jumala", "aamen", "halleluja", "pyhä", "henki", "maria", "isä", "poika", "vapahtaja", "messias", "jahve", "jehova"];
const theological_ar = ["الرب", "يسوع", "المسيح", "الله", "آمين", "هللويا", "الروح", "القدس", "مريم", "الآب", "الابن", "المخلص", "المسيّا", "يهوه", "يهوفا"];
const theological_el = ["κύριος", "ιησούς", "χριστός", "θεός", "αμήν", "αλληλούια", "άγιο", "πνεύμα", "μαρία", "πατέρας", "υιός", "σωτήρας", "μεσσίας", "γιαχβέ", "ιεχωβά"];


// --- PARTE 3: Combine as listas e exporte o resultado final ---

module.exports = {
  pt: [...pt, ...theological_pt],
  en: [...en, ...theological_en],
  es: [...es, ...theological_es],
  fr: [...fr, ...theological_fr],
  eo: [...eo, ...theological_eo],
  ru: [...ru, ...theological_ru],
  zh: [...zh, ...theological_zh],
  vi: [...vi, ...theological_vi],
  ro: [...ro, ...theological_ro],
  ko: [...ko, ...theological_ko],
  de: [...de, ...theological_de],
  fi: [...fi, ...theological_fi],
  ar: [...ar, ...theological_ar],
  el: [...el, ...theological_el],
};